#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Aug  7 15:04:51 2019

@author: franzk
"""

import numpy as np
from L1_functions import readimgpath, get_true_image, desmear_true_image
from mpl_toolkits.axes_grid1 import make_axes_locatable
import matplotlib.pyplot as plt

image_index = 0
image_display_adjustment = 10

image, header = readimgpath(
    "/home/franzk/Documents/MATS/L1_processing/data/2019-02-08 rand6/", image_index, 0
)

true_image = get_true_image(image, header)
mean_img = np.mean(true_image)

plt.figure()
ax = plt.gca()
im = ax.imshow(
    true_image,
    cmap="viridis",
    vmin=mean_img - image_display_adjustment,
    vmax=mean_img + image_display_adjustment,
)
plt.title("CCD image")
plt.xlabel("Pixels")
plt.ylabel("Pixels")
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
plt.colorbar(im, cax=cax)
plt.show()

desmeared_image = desmear_true_image(true_image, header)

pred_mean_img = np.mean(desmeared_image)

plt.figure()
ax = plt.gca()
im = ax.imshow(
    desmeared_image,
    cmap="viridis",
    vmin=pred_mean_img - image_display_adjustment,
    vmax=pred_mean_img + image_display_adjustment,
)
plt.title("Image with bad desmearing applied")
plt.xlabel("Pixels")
plt.ylabel("Pixels")
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
plt.colorbar(im, cax=cax)
plt.show()

print(
    "Image: "
    + str(image_index)
    + ", Leading blank: "
    + str(header["BlankLeadingValue"])
    + ", Trailing blank: "
    + str(header["BlankTrailingValue"])
)

