[tox]
envlist = py311,ty,lint
skipsdist = True

[testenv:py311]
deps =
    -rrequirements.txt
    -e..
    pytest
basepython = python3.11
setenv =
    TZ = utc
commands =
    pytest tests {posargs}

[testenv:ty]
basepython = python3.11
deps =
    -rrequirements.txt
    -e..
    pytest
    ty
commands =
    ty check app.py stacks level1b tests \
        --ignore unused-type-ignore-comment \
        --warn invalid-argument-type \
        --warn unresolved-import

[testenv:lint]
deps =
    ruff
    -e..
commands =
    ruff check --line-length 80 app.py stacks level1b tests

[pytest]
filterwarnings =
    once::DeprecationWarning
    once::PendingDeprecationWarning
